# dev tool — requires: python3, Pillow (pip install Pillow); not part of the runtime
#
# Consumes assets/sprites/gunner-sheet.png + gunner-mapping.json and emits:
#   - packages/client/src/sprites/gunner-data.ts  (generated, committed)
#   - assets/sprites/preview.png                  (labeled contact sheet)
#
# Deterministic: same inputs -> byte-identical outputs. Run from repo root:
#   python3 tools/gen-sprites.py
import base64
import json
import os
from PIL import Image, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEET = os.path.join(ROOT, "assets", "sprites", "gunner-sheet.png")
MAPPING = os.path.join(ROOT, "assets", "sprites", "gunner-mapping.json")
OUT_TS = os.path.join(ROOT, "packages", "client", "src", "sprites", "gunner-data.ts")
OUT_PREVIEW = os.path.join(ROOT, "assets", "sprites", "preview.png")

FRAME_W = 40
FRAME_H = 80
MAX_PALETTE = 31  # opaque colors; index 0 is reserved for transparent

DIR_ORDER = ["front", "front-left", "left", "back-left", "back"]


def load_mapping():
    with open(MAPPING) as fh:
        return json.load(fh)


def cell_key(cell):
    return (cell["r"], cell["c"])


def collect_unique_cells(mapping):
    """Unique (r,c) cells in stable mapping order; dedupe shared cells."""
    order = []
    seen = set()
    dirs = mapping["directions"]
    for name in DIR_ORDER:
        d = dirs[name]
        for cell in d["walk"]:
            k = cell_key(cell)
            if k not in seen:
                seen.add(k)
                order.append(k)
        k = cell_key(d["fire"])
        if k not in seen:
            seen.add(k)
            order.append(k)
    return order


def crop_frame(sheet, cellW, cellH, r, c):
    """Crop full cell, downscale to FRAME_W x FRAME_H (LANCZOS), binarize alpha."""
    box = (c * cellW, r * cellH, (c + 1) * cellW, (r + 1) * cellH)
    cell = sheet.crop(box).resize((FRAME_W, FRAME_H), Image.LANCZOS)
    px = cell.load()
    for y in range(FRAME_H):
        for x in range(FRAME_W):
            rr, gg, bb, aa = px[x, y]
            px[x, y] = (rr, gg, bb, 255 if aa >= 128 else 0)
    return cell


def build_palette(frames):
    """Adaptive-quantize all opaque pixels across every frame to <=31 colors.
    Returns a P-mode palette image used to remap each frame deterministically."""
    opaque = []
    for f in frames:
        px = f.load()
        for y in range(FRAME_H):
            for x in range(FRAME_W):
                rr, gg, bb, aa = px[x, y]
                if aa >= 128:
                    opaque.append((rr, gg, bb))
    comp = Image.new("RGB", (len(opaque), 1))
    comp.putdata(opaque)
    return comp.quantize(colors=MAX_PALETTE, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)


def index_frame(frame, pal_img):
    """Return bytes: 0 for transparent, else palette index in 1..31."""
    q = frame.convert("RGB").quantize(palette=pal_img, dither=Image.Dither.NONE)
    qdata = q.tobytes()
    adata = frame.getchannel("A").tobytes()
    return bytes((qdata[i] + 1) if adata[i] >= 128 else 0 for i in range(len(qdata)))


def emit_ts(cells, indexed, palette_rgb):
    max_idx = max((b for data in indexed.values() for b in data), default=0)
    # PALETTE[0] is the transparent placeholder; 1..max_idx are opaque colors.
    palette = [(0, 0, 0)] + [palette_rgb[i] for i in range(max_idx)]

    lines = []
    lines.append("// GENERATED by tools/gen-sprites.py — do not edit by hand.")
    lines.append("")
    lines.append(f"export const FRAME_W = {FRAME_W}")
    lines.append(f"export const FRAME_H = {FRAME_H}")
    lines.append("")
    lines.append("export type SpriteDir = 'front' | 'front-left' | 'left' | 'back-left' | 'back'")
    lines.append("")
    lines.append("export const PALETTE: ReadonlyArray<readonly [number, number, number]> = [")
    for (r, g, b) in palette:
        lines.append(f"  [{r}, {g}, {b}],")
    lines.append("]")
    lines.append("")
    lines.append("// Each frame is FRAME_W*FRAME_H palette-index bytes, base64-encoded.")
    lines.append("const F = (s: string): Uint8Array => new Uint8Array(Buffer.from(s, 'base64'))")
    lines.append("")
    var_of = {}
    for (r, c) in cells:
        name = f"f_{r}_{c}"
        var_of[(r, c)] = name
        b64 = base64.b64encode(indexed[(r, c)]).decode("ascii")
        lines.append(f"const {name} = F('{b64}')")
    lines.append("")

    def ref(cell):
        return var_of[cell_key(cell)]

    dirs = MAPPING_DATA["directions"]
    lines.append(
        "export const SPRITE_FRAMES: Record<SpriteDir, { walk: [Uint8Array, Uint8Array]; fire: Uint8Array }> = {"
    )
    for name in DIR_ORDER:
        d = dirs[name]
        w0, w1 = d["walk"]
        key = name if name in ("front", "back", "left") else f"'{name}'"
        lines.append(f"  {key}: {{ walk: [{ref(w0)}, {ref(w1)}], fire: {ref(d['fire'])} }},")
    lines.append("}")
    lines.append("")
    os.makedirs(os.path.dirname(OUT_TS), exist_ok=True)
    with open(OUT_TS, "w") as fh:
        fh.write("\n".join(lines))
    return max_idx, len(palette)


def render_preview(cells, indexed, palette_rgb):
    scale = 3
    cols = 5
    rows = (len(cells) + cols - 1) // cols
    label_h = 12
    pad = 6
    cw = FRAME_W * scale
    ch = FRAME_H * scale
    tile_w = cw + pad
    tile_h = ch + label_h + pad
    canvas = Image.new("RGB", (cols * tile_w + pad, rows * tile_h + pad), (210, 210, 210))
    draw = ImageDraw.Draw(canvas)
    for i, (r, c) in enumerate(cells):
        data = indexed[(r, c)]
        frame = Image.new("RGB", (FRAME_W, FRAME_H))
        fpx = frame.load()
        for y in range(FRAME_H):
            for x in range(FRAME_W):
                idx = data[y * FRAME_W + x]
                fpx[x, y] = (235, 235, 235) if idx == 0 else palette_rgb[idx - 1]
        big = frame.resize((cw, ch), Image.NEAREST)
        gx = pad + (i % cols) * tile_w
        gy = pad + (i // cols) * tile_h
        draw.text((gx, gy), f"{r},{c}", fill=(20, 20, 20))
        canvas.paste(big, (gx, gy + label_h))
    canvas.save(OUT_PREVIEW)


MAPPING_DATA = None


def main():
    global MAPPING_DATA
    MAPPING_DATA = load_mapping()
    cellW = MAPPING_DATA["cellW"]
    cellH = MAPPING_DATA["cellH"]
    sheet = Image.open(SHEET).convert("RGBA")

    cells = collect_unique_cells(MAPPING_DATA)
    frames = [crop_frame(sheet, cellW, cellH, r, c) for (r, c) in cells]
    pal_img = build_palette(frames)
    palette_rgb = []
    flat = pal_img.getpalette()
    for i in range(MAX_PALETTE):
        palette_rgb.append((flat[i * 3], flat[i * 3 + 1], flat[i * 3 + 2]))

    indexed = {cell: index_frame(frame, pal_img) for cell, frame in zip(cells, frames)}
    max_idx, pal_len = emit_ts(cells, indexed, palette_rgb)
    render_preview(cells, indexed, palette_rgb)
    print(f"gen-sprites: {len(cells)} unique frames, palette {pal_len} entries (max index {max_idx})")
    print(f"  wrote {os.path.relpath(OUT_TS, ROOT)}")
    print(f"  wrote {os.path.relpath(OUT_PREVIEW, ROOT)}")


if __name__ == "__main__":
    main()
